### ISSUE TITLE
Bug: App crash on selecting certain fields in DataSearch

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/batteries#17]
I have seen this behavior happen with the `gitxplore-live` app's dataset, using the description field.
![](https://i.imgur.com/NvxGjFa.png)

Likely cause is the fact that the field doesn't have sub-fields. It's not necessary for a field to have sub-fields.

**Comment by metagrover** [comment]
Fixed here: https://github.com/appbaseio/batteries/commit/582c5278d25e461b851ed6e246c882cb5a920bb8
