### ISSUE TITLE
Bug: Sort field logic in results isn't applied correctly

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/batteries#20]
We need to sort on `keyword` type or a `string` type with `index: not_analyzed` field. Apparently, the sort is being applied on a `field.string` value which isn't even a thing.

![](https://i.imgur.com/jk04DkV.png)

**Comment by metagrover** [comment]
Fixed here: https://github.com/appbaseio/batteries/commit/582c5278d25e461b851ed6e246c882cb5a920bb8

**Comment by metagrover** [comment]
Only show the applicable fields here as dataFields - fields having subfields of type: `keyword` or index: `not_analyzed` should be visible to the user incase of `text` or `string` fields.

This will only be applicable to the reactivelist component.

**Comment by siddharthlatest** [comment]
- [ ] The current **Search Preview** UI ignores the sort field logic. It should instead be set by default to **Best Match** (i.e. ES sorts it by relevance) and when a user selects a specific sort field, use that to sort on.

**Comment by jyash97** [comment]
Fixed in #82
