### ISSUE TITLE
Enhancement: Hide meta fields from the UI view

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/batteries#27]
Hide the meta fields from the result view. They don't add any aesthetic or functionality value, we can show `_id` in the file view mode.

![](https://i.imgur.com/9aXjAme.png)

**Comment by jyash97** [comment]
Fixed [here](https://github.com/appbaseio/batteries/commit/fbdb08184c7b553eb1ccf5e9b543e63a836474c8)
