### ISSUE TITLE
Enhancement: Search component

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/batteries#28]
## Improvements:

- [x] Make default search weights to be 1.
- [x] Can we make the search field selection to have a filter? (Many times, we have 100+ fields and browsing through them isn't a great experience) cc @metagrover 
- [ ] Improving the suggestions UI look and feel - this is just lacking right now in my subjective opinion. @metagrover 
- [x] There is some bug with highlighting, it doesn't always work.

**Comment by jyash97** [comment]
#44

**Comment by metagrover** [comment]
@jyash97 you can close this after completing everything (Point - 1) in the checklist.

Point 1 - should be trivial to fix.
Point 3 - will be implemented in the reactivesearch library.

**Comment by siddharthlatest** [comment]
- [ ] Point 1 is still open cc @jyash97
