### ISSUE TITLE
Enhancement: Result component

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/batteries#29]
## Improvement(s):

- [x] At the very basic, we should have a UI that looks sleek visually. A list UI is a good default instead of the current tree type UI structure. The whole object is visible anyways on hovering over the view / edit icon, so we should focus on the look and feel of the relevant search items instead.

- [x]  Allow a way for user to specify what elements appear in the layout - if we do this, it would replace the `includeFields` and `excludeFields` feature as it effectively does the same thing.

- [x] Either ways, we should remove `excludeFields` from this UI as it's an overkill.

**Comment by jyash97** [comment]
#43

**Comment by divyanshu013** [comment]
How to pass a render prop for the result component here?

**Comment by siddharthlatest** [comment]
@jyash97 Further notes -

The options in the UI should be in the following order:

1. Sort Field
2. Show Result Stats
3. Size
4. Show Pages
5. Stream
6. Customize List Preview

(We will remove Include / Exclude Fields and Loading Message options).

- [ ] There is a bug in how the *sortField* behavior works, it should be set to **Best Match** by default and then updated to the appropriate sorting option when selected by the user.
