### ISSUE TITLE
Feature: Support different layout templates

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/batteries#30]
We can get to this feature in a bit, but it's an important feature from a visual standpoint.

We can support three layouts for the results display:

1. List - this is the default layout,
2. Card / Grid - this is a secondary layout,
3. Map - this is the third layout if geopoint data is selected.

Alternatively, expose `onData` and `onAllData` props.

**Comment by siddharthlatest** [comment]
@jyash97 We should support **List** and **Card** options to begin with, this can be shown to the user using a radio button selection.

Also, this behavior can be shown directly in the *Edit view* of the Result component, no need to show a separate view.

**Comment by jyash97** [comment]
Added in #79 
For now we are showing in a different modal
