### ISSUE TITLE
Feature: Support DataSearch or CategorySearch

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/batteries#35]

**Comment by divyanshu013** [comment]
What's the prop and usage for this?

**Comment by jyash97** [comment]
#36 PR is not yet merged. 
After it has been merged you can pass `useCategorySearch` prop from sandbox wrapper to enable CategorySearch instead of DataSearch
```js
<SearchSandbox
 useCategorySearch
>
  ...
</SearchSandbox>
```
