### ISSUE TITLE
Relevant docs

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/batteries#49]
Would be nice to have some docs on usage for example https://github.com/appbaseio/batteries/issues/29, https://github.com/appbaseio/batteries/issues/34, https://github.com/appbaseio/batteries/issues/35

Also some dependencies are not mentioned in the readme properly. Docs are not maintained properly. For example the redux setup is unclear (also missing thunk middleware).

**Comment by jyash97** [comment]
Added in #83
