### ISSUE TITLE
Auth credentials are not getting set properly

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/batteries#58]
When `credentials` are provided, they should be used to correctly set the headers instead of the browser cookie.

**Comment by siddharthlatest** [comment]
@divyanshu013 Do you recollect which view was doing this? We checked on Search Preview - over there, we don't use cookies.

**Comment by divyanshu013** [comment]
I think this was happening in the plugin for analytics or search preview. Can't exactly recall. But this is probably already fixed in the latest commits here. Earlier I had to maintain a separate fork which had some unmerged PRs. If the plugin is working fine then this is probably fixed I think.
