### ISSUE TITLE
Bug: Exporting code in CodeSandbox

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/batteries#75]
While exporting code in codesandbox, following errors happen:

1. Instead of the DataSearch component, it displays `Nothing to Display`.

![](https://i.imgur.com/TY7mvej.png)

2. The ReactiveList component gets exported with an undefined componentId resulting in a library error. https://codesandbox.io/s/wkr64ny398

![](https://i.imgur.com/9ey5xXm.png)

**Comment by jyash97** [comment]
have fixed this in #76 , checked with different apps its working fine now. There is a formatting code issue which I will fix when this PR is merged.
